# theme settings
theme: "lone-wolf-theme"
remote_theme : "manid2/lone-wolf-theme"
bootswatch_theme: "cerulean" # cerulean, spacelab, united

# site settings, follows the order used in jekyll-seo-tag plugin
lang: "ja_JP"
title: "PokkeDoll"
description: "PokkeDoll offical site"
url: "https://pokkedoll.github.io" # site url e.g. "https://manid2.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
author: Emorard

logo: assets/images/favicons/icon-256x256.png # PNG is SEO friendly

# comments settings
comments:
  provider: false # false (default), "disqus", "discourse"
  disqus:
    # refer what is disqus shortname article online
    shortname:

# feed
atom_feed:
  path: # blank (default) uses feed.xml

# site search settings
search: # true, false (default)
search_full_content: # true, false (default)
search_provider: # google

google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore /docs in theme
  - /test # ignore /test in theme
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# site defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_hero: true
      show_author: true
      show_toc: true
      share: true
      show_comments: false
      show_ads: false
  # any page
  - scope:
      path: ""
    values:
      # for SEO and social sharing
      image: assets/images/favicons/icon-256x256.png
      image_alt: pokkedoll icon